name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v2.x
    - name: CreateFile
      uses: finnp/create-file-action@1.0.0
        with:
          FILE_NAME: /tmp/git_commit
          FILE_DATA: "${{ env.GITHUB_SHA_SHORT }}"
    - name: Build and push with cache
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: twistoywang
        password: ${{ secrets.PASSWORD }}
        image_name: twistoywang/develop-environment
        image_tag: latest,commit-${{ env.GITHUB_SHA_SHORT }}
        push_git_tag: true
        build_extra_args: "--build-arg=GITHUB_SHA_SHORT=${{ env.GITHUB_SHA_SHORT }}"
        stages_image_name: twistoywang/develop-environment-stage
