name: Nightly Build CI

on:
  schedule:
    - cron: "0 20 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Inject slug/short variables
      uses: rlespinasse/github-slug-action@v2.x
    - name: Get current date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
    - name: Build and push with cache
      uses: whoan/docker-build-with-cache-action@v5
      with:
        username: twistoywang
        password: ${{ secrets.PASSWORD }}
        pull_image_and_stages: false
        image_name: twistoywang/develop-environment
        image_tag: nightly-build-${{ steps.date.outputs.date }}
        push_git_tag: false
        stages_image_name: twistoywang/develop-environment-stage
